### ISSUE TITLE
Store and load models

### ISSUE THREAD

**Issue by monisha08041998** [kdis-lab/ExecuteMulan#1]
hi how can we store and load the model

**Comment by i02momuj** [comment]
Hello Monisha.

Actually, this tool is just though to be used to execute a wide range of multi-label classification models from Mulan library and get the results over a given test set, in order to compare them to other multi-label classification methods.
However, it does not provide the ability to store and load models nor other functionalities that are available using Mulan. For this purpose, I encourage you to use the original Mulan library: http://mulan.sourceforge.net/

Best.

**Comment by monisha08041998** [comment]
Hey,Thanks for your reply.I found the code to store and load modules in the original mulan repo https://www.javatips.net/api/Mulan-master/mulan/src/mulan/examples/StoringAndLoadingModels.java .ANy suggestions regarding the integration?

**Comment by i02momuj** [comment]
If you want to integrate it with this tool, maybe the execute() method of the executeMulan.MulanExecutor.java class would be a good option. If cross-validation is not selected (lines 130-160), it builds (line 133) and evaluates the model. So probably you could save the model after building it.

**Comment by monisha08041998** [comment]
Yes tried to integrate it.Can you just tell me the ways to jar the modified code?Sorry Im a newbie.

**Comment by i02momuj** [comment]
It would depend on the IDE you are using. For example, here are the instruction if you were using eclipse, but it would depend in each case. Best.
https://support.smartbear.com/alertsite/docs/monitors/web/selenium/export-eclipse-java-project-as-runnable-jar.html

**Comment by monisha08041998** [comment]
Hi Sorry,its asking for a manifest file how to provide it?

**Comment by monisha08041998** [comment]
Thanks a lot!!
