### ISSUE TITLE
Creating own jar file

### ISSUE THREAD

**Issue by monisha08041998** [kdis-lab/ExecuteMulan#2]
Hi I modified the code MulanExecutor.java ,now i need to convert it into the jar file.Before creating the jar file I need to compile all the files.How can it be done should I compile the main.java when I do so Iam getting many errors as all the packages are interrelated.It would be very helpful if you could suggest on how to proceed.Thanks in advance!

**Comment by i02momuj** [comment]
Hello Monisha. I cannot help you with that a lot, because it is more a technical issue of how to create a jar. I think you could open the whole code folder as a project in your preferred IDE, modify the class you need, and create the jar following the instructions that your IDE provides you. I hope that works.
